controllers/suite_test.go
Cherry-picked from upstream repo.
=> chore: disable string output size restriction in gomega

controllers/suite_test.go
Signed-off-by: Sunil Shivanand <sunil.shivanand@statnett.no>
=> test(go): disable caching Job objects

.github/workflows/ci.yml
This reverts commit 4ed59e4a064a8866637ae3895525aece9e969581.
As this seems unrelated to the issue we are trying to solve.
=> revert: "ci: run tests without the StepSecurity hardener (#36)"

.golangci.yml, api/v1alpha1/containerimagescan_types.go, api/v1alpha1/groupversion_info.go, api/v1alpha1/vulnerability.go, config/crd/bases/stas.statnett.no_containerimagescans.yaml, controllers/containerimagescan_controller.go, controllers/indexer.go, controllers/scan_job_controller.go, controllers/scan_job_controller_test.go, controllers/suite_test.go, controllers/types.go, controllers/workload_controller.go, controllers/workload_controller_test.go, internal/controller/reconcile.go, internal/controller/reconcile_test.go, internal/errors/errors.go, internal/errors/errors_test.go, internal/hash/strings.go, internal/metrics/collector.go, internal/metrics/collector_test.go, internal/resources/mapper.go, internal/trivy/scan_job.go, internal/yaml/resources.go, internal/yaml/resources_test.go, main.go, pkg/operator/config.go
=> ci(lint): rework golangci-lint config + code

.github/workflows/clear-cache.yaml
Based on https://stackoverflow.com/a/73556714/10759143.
Will be used to see if the cache might be the source of our current CI total failure.
=> chore: add manual workflow to clear cache

.github/workflows/clear-cache.yaml
Improve clear cache even more, by removing steps that might create new caches.
=> chore: improve clear cache workflow by not caching more

Makefile, config/e2e-test/kustomization.yaml
=> test(e2e): disable trivy server Service sessionAffinity

README.md
The *How it works* section looked a bit misplaced when it was in the contributing section.
Now it is under the section *Getting Started* , maybe not perfect that either. Should it be a `##` section?
=> docs: small reordering of paragraphs

Makefile, config/samples/stas_v1alpha1_containerimagescan.yaml, controllers/scan_job_controller_test.go, controllers/testdata/scan-job-successful/successful-scan-cis.yaml, controllers/testdata/scan-job-successful/successful-scan-job-pod.log.json, controllers/testdata/scan-job/cis.yaml, controllers/testdata/scan-job/expected-scan-job.yaml, controllers/testdata/scan-job/workload-pod.yaml, test/e2e/workload-scan/scan-cron-job/00-assert.yaml, test/e2e/workload-scan/scan-cron-job/00-create.yaml, test/e2e/workload-scan/scan-cron-job/01-assert.yaml, test/e2e/workload-scan/scan-daemon-set/00-assert.yaml, test/e2e/workload-scan/scan-daemon-set/00-create.yaml, test/e2e/workload-scan/scan-daemon-set/01-assert.yaml, test/e2e/workload-scan/scan-deployment/00-assert.yaml, test/e2e/workload-scan/scan-deployment/00-create.yaml, test/e2e/workload-scan/scan-deployment/01-assert.yaml, test/e2e/workload-scan/scan-job/00-assert.yaml, test/e2e/workload-scan/scan-job/00-create.yaml, test/e2e/workload-scan/scan-job/01-assert.yaml, test/e2e/workload-scan/scan-pod/00-assert.yaml, test/e2e/workload-scan/scan-pod/00-create.yaml, test/e2e/workload-scan/scan-pod/01-assert.yaml, test/e2e/workload-scan/scan-replica-set/00-assert.yaml, test/e2e/workload-scan/scan-replica-set/00-create.yaml, test/e2e/workload-scan/scan-replica-set/01-assert.yaml, test/e2e/workload-scan/scan-stateful-set/00-assert.yaml, test/e2e/workload-scan/scan-stateful-set/00-create.yaml, test/e2e/workload-scan/scan-stateful-set/01-assert.yaml
An image with less vulnerabilities.
=> test: bump nginx-unprivileged image digest to newer image

.github/workflows/ci.yml, .markdownlint.yaml, .markdownlintignore
=> ci(lint): add markdown linting

Makefile, internal/controller/stas/scan_job_controller_test.go, internal/controller/stas/workload_controller_test.go
=> ci(test): increase timeout and add -race flag

.github/workflows/clean-ghcr.yaml
Close #97 
Kudos to @bendikp ref. https://github.com/statnett/image-scanner-operator/issues/97#issuecomment-1398153363
=> ci(fix): daily cron expression of GHCR cleanup

.github/workflows/ci.yml, internal/controller/stas/suite_test.go
=> ci(test): attach envtest output to debug test failures

cmd/main.go, pkg/operator/config.go
This breaks up the main func into logical steps. I hope we are able to make this code more testable now.
Relates to #81
=> refactor: break up main func

cmd/main.go, pkg/operator/config.go
This reverts commit e494eedb596ffcf94b37dcdcd6209f2e00fa8d87.
It seems like this made the controller unable to start, and the e2e-tests on the branch passed - which indicates something wrong with our e2e-test setup. I will create an issue for that.
=> revert: "refactor: break up main func (#115)"

internal/controller/stas/scan_job_controller.go
=> ci(debug-test): add debug lines to aide with debugging

docs/architecture.puml
I am planning to use the architecture diagram in a presentation, and discovered some shortcomings when preparing. This fixes this. Removing some metadata and grouping to simplify and get a decent layout.
Preview:
=> docs: update architecture diagram

cmd/main.go, pkg/operator/config.go
Improved version of https://github.com/statnett/image-scanner-operator/pull/118, now with correct handling of `pflag.FlagSet`. We should probably wait for https://github.com/statnett/image-scanner-operator/pull/126 to ensure this is not breaking everything again....
=> refactor: break up main func (take 2)

.github/workflows/ci.yml, Makefile, config/manager/kustomization.yaml, kustomization.yaml
=> chore: add dummy registry host to local/ci image to make it fully qualified

.github/workflows/ci.yml
Close #151 
It seems like Dependabot does not understand the releases....
=> ci(fix): upgrade tj-actions/verify-changed-files

internal/controller/stas/scan_job_controller.go
Signed-off-by: Sunil Shivanand <sunil.shivanand@statnett.no>
Fixes #164.
=> fix: do not log DEBUG lines by default

internal/controller/stas/scan_job_controller_test.go, internal/controller/stas/suite_test.go, internal/controller/stas/workload_controller_test.go
I discovered some minor bugs/improvements to tests while working on https://github.com/statnett/image-scanner-operator/pull/192.
=> test: add missing asserts and drop some eventually

internal/controller/stas/containerimagescan_controller.go
This PR is an attempt to fix two issues related to rescanning of images:
1. When redeploying/updating the operator, it seems like all images are rescanned. This is caused by the controller-runtime behavior to create reconcile events for all resources on startup. To fix this, I added logic to check the last **successful** scan time before admitting a CIS through the reconcile loop.
2. Trivy scanning seems to fail quite frequently. To mend this, we used to have retries on jobs. This turned out to be a bad approach in some corner cases. But we are still struggling with this, especially in the e2e-tests. So in this PR, I suggest deleting an existing scan job and re-queue the request if the reconcile "gatekeeper" added in 1 decides that the image should be rescanned.
=> fix: rescan machinery

config/rbac/role.yaml, internal/controller/stas/containerimagescan_controller.go
Add a missing RBAC to be able to delete Jobs and make sure the pods from jobs are also deleted
=> fix: add missing RBAC and ensure job pods are deleted

config/rbac/role.yaml, internal/controller/stas/predicates.go, internal/controller/stas/scan_job_backoff_pod_controller_test.go, internal/controller/stas/scan_job_controller.go, internal/controller/stas/scan_job_controller_test.go, internal/controller/stas/suite_test.go, internal/controller/stas/testdata/scan-job-backoff-pod/cis.yaml, internal/errors/errors.go, internal/operator/operator.go
=> fix: ensure back-off scan jobs are deleted

.github/workflows/ci.yml
=> ci(e2e): try larger runners

Makefile
To fix https://github.com/statnett/image-scanner-operator/pull/529
=> ci(renovate): fix kustomize marker

.github/workflows/clean-ghcr.yaml
Reverts statnett/image-scanner-operator#606
=> revert: "ci: try GHCR cleanup with Statnett BOT token"

.github/renovate.json5
We have enabled code owner approval, so this does not mean complete auto-merge, but auto-merge after 1 approval of the @statnett/stas team.
=> ci(renovate): automerge minor and digest

.github/workflows/ci.yml
Fixes https://github.com/statnett/image-scanner-operator/security/dependabot/4.
=> ci: fix verify-changed-files GHA security advisory

.github/workflows/ci.yml
Reverts statnett/image-scanner-operator#754
=> revert: "ci: fix verify-changed-files GHA security advisory"

.gitignore, Makefile
This PR is a minor improvement of the migration to chainsaw, ref. https://github.com/statnett/image-scanner-operator/pull/794
=> test(e2e): improve chainsaw configuration

internal/operator/operator.go
Ref. https://github.com/statnett/image-scanner-operator/pull/870
=> chore: simplify code reported by latest golangci-lint

internal/controller/stas/containerimagescan_controller.go, internal/controller/stas/containerimagescan_status.go, internal/controller/stas/scan_job_controller.go, internal/controller/stas/ssa_client.go, internal/controller/stas/workload_controller.go
This PR migrates CIS status updates to SSA and finalizes the migration to SSA in this operator.
=> chore: use server-side-apply for CIS status

internal/controller/stas/containerimagescan_status.go, internal/controller/stas/scan_job_controller.go
This is a refactoring extracted from https://github.com/statnett/image-scanner-operator/pull/1030. I prefer having a similar set of functions for building CIS patches and PolicyReports (maybe a future interface).
=> refactor: preparations for PolicyReport
