statnett/image-scanner-operator

- .github/workflows/ci.yml
It seems like golangci-lint needs more time when no cache is present. This PR increases the timeout (as suggested by the logged error) to 5 minutes.
> ci: increase golangci-lint-action timeout

- .github/workflows/build.yaml
- .github/workflows/ci.yml
- Dockerfile
This PR adds building the container image, which will later be used by the e2e-tests in a follow-up PR and to build release images.
> ci: add container image build

- test/e2e-config/kuttl-test.yaml
- test/e2e/scenario/vulnerability-overflow/00-assert.yaml
Hopefully, this will make the e2e tests less fragile. The default timeout is 30 seconds, ref. https://kuttl.dev/docs/testing/reference.html#testassert
~~Also updating the asserted `minSeverity`, which appears to have changed.~~
> test(e2e): increase timeout in vulnerability-overflow test

- test/e2e/scenario/vulnerability-overflow/00-assert.yaml
Give the vulnerability-overflow test step a bit more head room. Closes #19
> test(e2e): increase timeout in vulnerability-overflow test, take two

- README.md
- config/samples/stas_v1alpha1_containerimagescan.yaml
This PR attempt to document the CIS CRD (using https://doc.crds.dev/), including user-facing annotations that can be added to pods to influence the image scanning.
> docs: add CIS CRD docs

- .github/workflows/build.yaml
This adds building and pushing images to pull requests. It must run on the `pull_request_target` to get permission to push to the container registry.
If this works, I hope it could avoid the image import in the CI e2e-test, and hopefully mend https://github.com/statnett/image-scanner-operator/issues/21.
Also, we should also add container repository pruning in a follow-up PR. But let's first see if it works.
> ci(docker): build and push images for pull requests

- .github/workflows/release-please.yml
- README.md
- config/manager/kustomization.yaml
- kustomization.yaml
This will make the release-please workflow update the operator image tag in the release PR. This has been tested in https://github.com/erikgb/operator-ci-test. See https://github.com/erikgb/operator-ci-test/pull/12 for an example on how this might look like.
~~Running the e2e-tests locally will now modify a file that should not be committed to Git, but I have an idea on how to fix that. Probably by introducing a tailored e2e kustomize overlay.~~ Update: Added a new customization file in root folder. This will also allow for simpler install of the operator. See installation of prometheus-operator as an example:
https://github.com/statnett/image-scanner-operator/blob/280b3a10f4611587d181cba7c0e500a7cd4477c4/config/deploy-dependencies/prometheus-operator/kustomization.yaml#L5
Which refers to …
> ci(release): make release-please workflow update image tag

- .github/workflows/ci.yml
- .yamllint.yaml
This PR uses the image pushed to GHCR for pull requests (https://github.com/statnett/image-scanner-operator/pull/30) in the e2e-tests. Thus avoiding the image import into the e2e cluster.
Closes https://github.com/statnett/image-scanner-operator/issues/21
> test(e2e): use image in GHCR for PR in e2e-tests

- .github/workflows/ci.yml
It seems like we use the wrong property in the [github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) to obtain the short branch name.
See https://github.com/statnett/image-scanner-operator/actions/runs/3900778458/jobs/6661883753
> ci(fix): use correct image tag on branch builds

- .github/workflows/lint-pr.yml
To ensure more consistent commit messages and changelog, I suggest adding validation of the PR title subject part. See https://github.com/amannn/action-semantic-pull-request#configuration for additional details.
> chore: stricter validation of PR title subject

- go.mod
- main.go
Since client-go uses klog as logger, we need to initialize klog to use our default zap-logger. This will ensure a consistent format for all operator logs.
> fix(log): initialize klog to get consistent log format

- config/manager/kustomization.yaml
- config/trivy-server/stateful_set.yaml
This bumps trivy to the latest release.
Could we make Dependabot (or Renovate) fix these tasks?
> build(deps): bump aquasecurity/trivy from 0.35.0 to 0.36.1

- .github/workflows/release-please.yml
Using a PAT should allow release workflows to run. See https://github.com/google-github-actions/release-please-action#github-credentials.
Even if the same suggests a bot behind the PAT, the token is currently issued from my personal account. Expires on Wed, Apr 12, 2023.
> chore(release): configure PAT for release-please

- .github/workflows/clear-cache.yaml
The current "clear cache" only nukes 10 caches each time. This is an improvement that deletes 100 caches for each run.
Based on https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
> chore: improved clear cache

- controllers/containerimagescan_controller.go
This PR adds a missing GenerationChangedPredicate to CIS controller setup, and will avoid some unnecessary reconciles that could potentially create duplicate jobs.
Extracted from https://github.com/statnett/image-scanner-operator/pull/48
> fix: add GenerationChangedPredicate to CIS controller

- main.go
In our docs we describe how to list operator settings:
But this does not work after https://github.com/statnett/image-scanner-operator/pull/29. The problem seems to be that after we add a help-flag, we need to implement the behavior.
> fix(cli): should print help when requested

- .github/workflows/ci.yml
This reverts commit fb99134adb27c176d5fc064c95253e3218bfce6a.
https://github.com/statnett/image-scanner-operator/pull/48 seems to fix the e2e-test issues.
> revert: "ci(e2e-test): disable e2e testing in CI for now (#63)"

- api/v1alpha1/labels.go
- controllers/containerimagescan_controller.go
- controllers/containerimagescan_controller_test.go
- controllers/testdata/scan-job/expected-scan-job.yaml
- controllers/workload_controller.go
- internal/trivy/scan_job.go
The main purpose of this PR is to address the fragile tests we have been seeing in #19 and #27. After the investigation performed by @padlar, it seems like the underlying cause might be duplicate jobs. So I took a closer look, and using `generateName` in a controller seems like a bad idea - since the name will be a random one and not deterministic. 
So this PR replaces use of `generateName` with a deterministic name, composed by CIS name, spec and namespace. But since a Kubernetes job has a `name` max length of 63 characters, we need to do this "smart".
Finally I found some constants in an api-machinery package for these max length values.
The e2e-tests seems to work again after this PR, so we should re-enable them in a follow-up PR. Ref. …
> fix: don't use generateName when creating jobs

- test/e2e/scenario/vulnerability-overflow/00-assert.yaml
This PR enables kuttl collectors for the e2e-test that seems most fragile. Ref. https://github.com/statnett/image-scanner-operator/issues/19
> test(e2e): try out kuttl collectors

- controllers/suite_test.go
This reverts commit 74dc3df160fee0a6fbd1e33144b1615a783bf9a9.
> revert: "test(go): disable caching Job objects (#41)"

- Makefile
- config/crd/bases/stas.statnett.no_containerimagescans.yaml
- test/e2e-config/k3d-config.yml
This bumps controller-tools, controller-gen and k3s versions to K8s 1.26 compliant versions.
> test: bump K8s version to 1.26

- api/v1alpha1/labels.go
- controllers/testdata/scan-job/cis.yaml
- controllers/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
- test/e2e/scenario/vulnerability-overflow/00-assert.yaml
This adds extra labels to the scan Job with information about the workload that is being scanned. This will make it easier to debug the e2e-tests that are failing.
> feat: add workload labels on the scan job

- controllers/containerimagescan_controller_test.go
- controllers/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
#80 only added labels to the scan Job, this PR also adds workload labels to the scan Pod.
Related to #19
> fix: add workload labels to the podTemplate in the scan Job

- internal/controller/stas/suite_test.go
- internal/controller/stas/types.go
- internal/controller/stas/types_test.go
- internal/controller/stas/workload_controller.go
This PR changes to workload controller to obtain image tags from pod spec containers, instead of pod status containerstatuses. This should fix #85.
User-facing change is that tag is now unset in CIS if user did not specify a tag. Previously it would get the `latest` value.
> fix: obtain image tags from pod container spec

- README.md
Adding badges will add more visibility to the current status of the project. Leaving out CI for now - until we get more stability on the e2e-tests, ref. https://github.com/statnett/image-scanner-operator/issues/27 https://github.com/statnett/image-scanner-operator/issues/19.
> docs: add initial badges to README.md

- .github/workflows/ci.yml
Which should speed up the overall running checks time.
There is no "real" dependency from e2e-test to test. The e2e-tests require that the operator image is available, but there is no way to specify dependencies across workflows. It this becomes a problem, there are workarounds available.
> ci(perf): allow e2e-test to run parallel to test

- .github/workflows/clean-ghcr.yaml
Quote schedule cron expression, ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
Closes #97
> ci(fix): use single quotes in schedule in prune ghcr workflow

- test/e2e/scenario/vulnerability-overflow/00-assert.yaml
This reconfigures the collectors for the flaky e2e-test, ref. https://github.com/statnett/image-scanner-operator/issues/19. Trying to get as much info as possible from assumed relevant stuff.
> ci(e2e): reconfigure collectors for flaky e2e-test

- config/e2e-test/kustomization.yaml
To avoid persistent volume issues, and because we don't need it, this PR replaces the PVC requested by the trivy server StatefulSet with a simple emptyDir.
Also replacing the JSON patch for `sessionAffinity` with a strategic merge patch - to avoid mixing patch strategies.
> test(e2e): replace trivy server cache PVC with emptyDir

- .github/workflows/ci.yml
Do dig further into the flaky e2e-test, this PR will ensure that all pod logs are uploaded as GH artifacts on job failure.
Also outputting the vuln scan job pods YAML in case this fails - as this is the test we have be struggling with.
> ci(e2e): upload pod logs as artifact on failure

- cmd/main.go
This PR is the first step towards splitting up the main func. I have tried to use a consistent code-style where the goal is to separate the function into the following parts:
1. Configure all supported flags. This will serve as the base for operator configuration.
2. Wiring up the config components, tying together flags, pflags and viper including the configuration of these.
3. Validation of configuration.
4. Bootstrapping the operator based on the configuration using viper.
Relates to #81
> refactor: consistent organization of code in main

- cmd/main.go
- internal/metrics/collector.go
- internal/metrics/collector_test.go
- pkg/operator/config.go
This moves the remaining operator config properties into the `Config` struct to improve consistency in the code. We should probably have a brush-up of the flag naming, but that will have to be in a follow-up PR.
Relates to #81
> refactor: move config properties to Config struct

- cmd/main.go
- config/image-scanner-jobs/kustomization.yaml
- config/manager/kustomization.yaml
- internal/controller/stas/suite_test.go
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
Close #109 
BREAKING CHANGE: This moves the configuration of Trivy server from the operator configmap to the new configmap for scan jobs. Any admins overriding the default value will is required to update their configuration.
> feat(admin)!: kustomizeable configmap for scan job default configuration

- renovate.json
Renovate config with Go and GitHub-actions disabled, as these will be handled by Dependabot.
Closing #127 
All commits will be of semantic type `build(deps)` because of [the preset `:semanticCommitTypeAll(build)`](https://docs.renovatebot.com/presets-default/#semanticcommittypeallarg0).
> chore: init Renovate config

- .github/renovate.json
At present it seems to me like Renovate will suggest PRs for ci, and not build, dependencies. To avoid these popping up in the release notes, without adjusting the PR titles, I suggest making ci the default `semanticCommitTypeAll` in the Renovate config.
Also moving the file to .github directory to avoid having too many files in the root directory.
> chore: adjust semanticCommitTypeAll Renovate config

- .github/workflows/build-image.yaml
- .github/workflows/ci.yml
I suspect that running the e2e-test image in a pull_request_target might mess up something, ref. #119. This PR embeds the image building in the e2e-test job.
Update: I think understand what might have happened on the PR that got merged with error: After simulating the error on this branch, I notice that building the image takes considerable time. This could result in the e2e-tests running on an outdated digest for the PR tag (race condition).
It is [not possible to have job dependencies across workflows](https://github.com/orgs/community/discussions/26632#discussioncomment-3252616), so I think we are better off with the approach suggested in this PR. If we still want to get GHCR image tags for pull requests, I think we have to do the e2e-testing in the same workflow as the image build. …
> ci: embed image build in e2e-test job

- .github/renovate.json5
Dependabot adds the label `dependencies` to all PRs, adding it here as well to make it consistent.
Also renaming file to json5, to support trailing commas and comments.
> chore(renovate): add 'dependencies' label to PRs

- internal/operator/operator.go
Closes #142.
Before the logger
```
➜  image-scanner-operator git:(init-logger) ✗ ./bin/manager
```
After the call to SetupLogger (console encoder)
```
image-scanner-operator git:(init-logger) ✗ ./bin/manager
2023-01-26T15:35:50.911+0100	INFO	setup	required flag/env not set	{"flag": "scan-job-namespace", "env": "SCAN_JOB_NAMESPACE"}
```
With the SetupLogger with the default Json Encoder
```
➜  image-scanner-operator git:(init-logger) ✗ ./bin/manager
{"level":"info","ts":"2023-01-26T14:25:13+01:00","logger":"setup","msg":"required flag/env not set","flag":"scan-job-namespace","env":"SCAN_JOB_NAMESPACE"}
```
> fix: init temporary logger to print errors during startup

- .github/renovate.json5
- test/e2e-config/k3d-config.yml
Closing #144 
This does two things:
* adding a new regex manager that can be used in YAML files where we have dependencies on the form (with examples of using this regex manager in the comment):
* ```yaml
image: some-docker/image:v3.0.0-slim
```
* ```yaml
SOME_IMAGE: another-image/foo:v8
```
* applies this new regex manager to the k3s image
> chore: enable renovating of rancher/k3s image

- cmd/main.go
- config/manager/kustomization.yaml
- go.mod
- internal/config/config.go
- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/predicates.go
- internal/controller/stas/workload_controller.go
- internal/operator/decode_hooks.go
- internal/operator/operator.go
- internal/operator/operator_test.go
- internal/operator/suite_test.go
This PR makes the regexp for excluding namespaces from scanning, typically system namespaces, configurable. While this feature might be useful for some, the plan is to add an equivalent configurable property for namespaces to include. And this will allow us to avoid scanning anything other than the workload images under test in our e2e-tests.
> feat(cli): make regexp for excluded namespace configurable

- config/e2e-test/kustomization.yaml
- internal/config/config.go
- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/workload_controller.go
- internal/operator/operator.go
This adds a configurable opt-in to include namespaces by regexp. Also reconfiguring the e2e-tests to only include kuttl-namespaces.
> feat(cli): make regexp for included namespace configurable

- .github/renovate.json5
Renovate is currently ignoring:
```json
"ignorePaths": [
"**/node_modules/**",
"**/bower_components/**",
"**/vendor/**",
"**/examples/**",
"**/__tests__/**",
"**/test/**",
"**/tests/**",
"**/__fixtures__/**"
]
```
This makes Renovate skip all updates in https://github.com/statnett/image-scanner-operator/tree/main/test.
> chore(renovate): un-ignore 'test' folder

- cmd/main.go
- internal/config/config.go
- internal/operator/operator.go
Somehow during the refactoring on the main func, we seem to have lost the ability to configure the zap-logger. Example:
```
2023-02-01T21:30:08.363Z INFO Reconciling {"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"max-job-27921450-z76pf","namespace":"deploy-playground"}, "namespace": "deploy-playground", "name": "max-job-27921450-z76pf", "reconcileID": "88f4129d-f48e-42eb-9399-42595c88089a"}
2023-02-01T21:31:10.330Z INFO Reconciling {"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"max-job-1-27921451-ql76l","namespace":"deploy-playground"}, "namespace": "deploy-playground", "name": "max-job-1-27921451-ql76l", "reconcileID": "85b367b0-2122-4db3-8892-d5be0b9136a7"}
2023-02-01T21:31:10.374Z INFO Reconciling …
```
> fix: make logger configurable again

- .github/renovate.json5
- config/manager/kustomization.yaml
- config/trivy-server/stateful_set.yaml
Closes https://github.com/statnett/image-scanner-operator/issues/162
This will make Renovate suggest updates for `ghcr.io/aquasecurity/trivy`.
A minor change was needed for the matcher regex to support `=` symbol.
> chore: renovate trivy docker image

- config/trivy-server/kustomization.yaml
Since they configure the default value. And `SKIP_UPDATE` is also deprecated in Trivy 0.37.x +.
> chore: remove obsolete Trivy server config

- .github/workflows/ci.yml
This will enable better control, and not have an implicit upgrade by upgrading the GHA, ref. https://github.com/AbsaOSS/k3d-action#version-mapping-and-override
Hopefully, we can get Renovate to suggest upgrades. @mikaelol
> ci: use explicit version of k3d

- internal/resources/suite_test.go
Ginkgo automatically cleans up on receving signals, so no need to explicitly setup handlers.
fixes #145.
> ci(test): fix data race in go tests

- internal/operator/operator.go
This overwrites the logger setup via user input.
Signed-off-by: Sunil Shivanand <padlar@live.com>
Output after the fix
```
➜  image-scanner-operator git:(fix-json-logging) ✗ make build && ZAP_ENCODER=console ZAP_LOG_LEVEL=info SCAN_JOB_NAMESPACE=default ./bin/manager
test -s /Users/padlar/sandbox/image-scanner-operator/bin/controller-gen && /Users/padlar/sandbox/image-scanner-operator/bin/controller-gen --version | grep -q v0.11.1 || \
GOBIN=/Users/padlar/sandbox/image-scanner-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.1
/Users/padlar/sandbox/image-scanner-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go build -o bin/manager cmd/main.go
1.675378643643044e+09	INFO	controller-runtime.metrics …
```
> fix: don't override user logging configuration

- .github/renovate.json5
Closes https://github.com/statnett/image-scanner-operator/issues/173
This will make upcoming PRs for trivy look like:
```
build(deps): update ghcr.io/aquasecurity/trivy docker tag to v0.37.1
```
instead of 
```
ci(deps): update ghcr.io/aquasecurity/trivy docker tag to v0.37.1
```
> chore(renovate): trivy PRs should have 'build' title

- .github/renovate.json5
- .github/workflows/ci.yml
Closes https://github.com/statnett/image-scanner-operator/issues/175
Adding the "universal" regex matcher we have previously used on-premises.
Using this universal matcher to make renovate match k3d and kuttl.
This matcher will match all of these:
* ```
renovate: datasource=something depName=something
version: 0.0.0
```
* ```
renovate: datasource=some-datasource depName=any-depname versioning=some-versioning
SOME_VERSION: 0.0.0
```
* ```
renovate: datasource=something depName=something
tag: 0.0.0
```
* ```
renovate: datasource=something depName=something registryUrl=custom-registry
another_tag: 0.0
```
* ```
renovate: datasource=something depName=something versioning=some-versioning registryUrl=custom-registry
ANY_TAG: 0
```
and many more variants.
> chore(renovate): add universal regex and match k3d/kuttl

- .github/workflows/ci.yml
- CONTRIBUTING.md
- Makefile
enable trace and verbose modes. Run the test suite 3 times to debug flaky tests.
Related to #27.
> ci(test): use ginkgo to run go tests

- README.md
- config/default/kustomization.yaml
- config/e2e-test/kustomization.yaml
- config/image-scanner-jobs/kustomization.yaml
- config/manager/kustomization.yaml
- config/manager/manager_patch.yaml
- config/trivy-server/kustomization.yaml
- config/trivy-server/stateful_set.yaml
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
When upgrading to the 0.2.0 release, I noticed that I had to qualify configmaps with namespace because both the Trivy server and Trivy jobs config map is named `trivy`.
BREAKING CHANGE: This renames all configmaps which will require changes if kustomized.
> fix!: should have unique config map names

- test/e2e/scenario/vulnerability-overflow/00-assert.yaml
This test has been failing 100% for the last couple of days, and I was able to reproduce the problem locally. It seems like an update to the vuln DB has made the test image even more vulnerable.
> test(e2e): fix test after image got more vulnerable

- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
Instead of fixing the code to handle scan job retries properly, ref. https://github.com/statnett/image-scanner-operator/pull/192, we decided to drop retries for now.
> fix: never retry scan job

- internal/config/config.go
- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/predicates.go
We've had issues with the rescan logic as it seems like all/most CIS resources are reconciled when the operator is restarted. This is very unfortunate, especially in large clusters, resulting is a resource consumption burst.
@bendikp has performed some testing locally, and it seems like our logic for returning `RequeueAfter` when reconciling CIS must always be set. We assumed that we were "saved" by the default 10h `SyncPeriod`, but it seems like the sync events are filtered out - probably by the generation-changed predicate.
This PR tries to use predicates to highlight the two difference scan/rescan paths: scan/rescan because of CIS spec change (generation changed) OR rescan due (time based).
> fix: always set RequeueAfter when reconciling CIS

- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
Renamed upstream: https://github.com/aquasecurity/trivy/pull/3467
> chore: rename Trivy config param

- go.mod
- go.sum
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/controller/stas/workload_controller.go
- internal/controller/stas/workload_controller_test.go
- internal/hash/strings.go
- internal/trivy/scan_job.go
- test/e2e/scenario/vulnerability-overflow/00-assert.yaml
- test/e2e/scenario/vulnerability-overflow/00-errors.yaml
- test/e2e/workload-scan/scan-cron-job/00-assert.yaml
- test/e2e/workload-scan/scan-cron-job/01-assert.yaml
- test/e2e/workload-scan/scan-daemon-set/00-assert.yaml
- test/e2e/workload-scan/scan-daemon-set/01-assert.yaml
- test/e2e/workload-scan/scan-deployment/00-assert.yaml
- test/e2e/workload-scan/scan-deployment/01-assert.yaml
- test/e2e/workload-scan/scan-job/00-assert.yaml
- test/e2e/workload-scan/scan-job/01-assert.yaml
- test/e2e/workload-scan/scan-pod/00-assert.yaml
- test/e2e/workload-scan/scan-pod/01-assert.yaml
- test/e2e/workload-scan/scan-replica-set/00-assert.yaml
- test/e2e/workload-scan/scan-replica-set/01-assert.yaml
- test/e2e/workload-scan/scan-stateful-set/00-assert.yaml
- test/e2e/workload-scan/scan-stateful-set/01-assert.yaml
It seems like we are having an issue with scan job names not being idempotent in some cases. Attempting to replace our custom hash function with mitchellh/hashstructure.
BREAKING CHANGE: This will result in new CIS names that will appear as duplicates. It is advised to reinstall the operator on upgrade.
> fix!: introduce mitchellh/hashstructure for hashing

- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/containerimagescan_controller_test.go
- internal/controller/stas/predicates.go
- internal/controller/stas/rescan.go
- internal/controller/stas/scan_job_controller_test.go
- internal/controller/stas/suite_test.go
- internal/operator/operator.go
After many issues with the rescan logic, based on `RequeueAfter`, I propose to instead use a ticker to trigger a recurring job that submits events for rescans that are due. The tick interval is currently hardcoded to 1 minute, but we could also make it configurable.
> fix: rescan based on ticker

- api/stas/v1alpha1/containerimagescan_types.go
- config/crd/bases/stas.statnett.no_containerimagescans.yaml
- internal/controller/stas/scan_job_controller.go
- internal/controller/stas/scan_job_controller_test.go
After we moved away from using `generateName` for scan jobs, the rescan job gets the same name as the scan job. This results in the CIS not being updated from new scan jobs. This PR suggests to use the UID of the scan job instead of the name.
**Maybe we should consider this change as breaking?**
> fix: use last scan job UID instead of name

- internal/controller/stas/predicates.go
- internal/controller/stas/scan_job_controller.go
- internal/controller/stas/scan_job_controller_test.go
This is a preparation PR before adding a concurrent scan jobs limit feature. Since a controller manager index can only index string fields, we need to migrate to job conditions instead of explicit job status fields. Also better aligned with Kubernetes logic, ref. https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/utils.go#L24-L33
> refactor: use job conditions

- config/trivy-server/stateful_set.yaml
It seems like requesting 5Gi persistence for Trivy server by default seems way too much. We are using around 300MB in our clusters currently, and it does not seem to increase significantly.
> fix: request smaller PV for trivy server cache

- config/e2e-test/kustomization.yaml
I wonder if we should use the "slow" mode by default, and this PR tries it out for the e2e-tests.
> chore: run scan jobs in "slow" mode in e2e-tests

- config/image-scanner-jobs/resource_quota.yaml
- internal/config/config.go
- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/indexer.go
- internal/controller/stas/predicates.go
- internal/controller/stas/scan_job_controller.go
- internal/operator/operator.go
While ResourceQuotas is a good safety guard, it does not seem to work well for limiting the workload scheduled by controllers. The number of events created by hitting the resource quota limit can be quite significant and not acceptable.
This PR adds a mechanism for limiting the number of jobs created by the operator - based on the current number of active scan jobs. The limit is configurable with a current default value of `8`. The suggested default is based on the current limitations in the configured resource quota and requests/limits on the scan job container. I'll suggest reviewing the overall configuration in a follow-up PR.
> fix: max active scan job limit

- .github/workflows/clean-ghcr.yaml
We are having issues with GHCR cleanup workflow. It currently runs only scheduled. This PR allows the workflow to be triggered manually.
> ci: add manual trigger for clean GHCR workflow

- .github/workflows/ci.yml
- Makefile
- config/manager/kustomization.yaml
I noticed a comment on https://microk8s.io/docs/registry-images:
> Note that containerd will not cache images with the latest tag so make sure you avoid it.
So this PR changes the build/CI image tag from `latest` to `dev`.
> build: don't use latest image tag

- internal/controller/stas/scan_job_backoff_pod_controller_test.go
- internal/controller/stas/scan_job_controller.go
We must ensure scan job pod is deleted when deleting scan job. Currently the pod seems to be orphaned causing panic on next reconcile. Also adding a safety-guard if this happens again, to get a meaningful error - instead of the current panic.
> fix: ensure job pod is deleted when deleting scan job

- internal/controller/stas/scan_job_controller.go
We are struggling with reconciliation errors for unsuccessful scan jobs:
```json
{"level":"error","ts":"2023-02-26T06:15:31.187Z","msg":"Reconciler error","controller":"backOffScanJobPod","namespace":"image-scanner-jobs","name":"<pod-name>","reconcileID":"a5540570-c9c8-4a66-8cd7-8927b891c198","error":"no container-state waiting found with reasons [\"ImagePullBackOff\" \"ErrImagePull\"] in pod \""<pod-name>","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k …
```
> fix: add debug logging for container state waiting

- internal/controller/stas/scan_job_controller.go
This is a follow-up to https://github.com/statnett/image-scanner-operator/pull/236. After installing the latest release in our cluster, we observe the following improved logging:
```json
{"level":"error","ts":"2023-02-27T14:43:13.854Z","msg":"Reconciler error","controller":"backOffScanJobPod","namespace":"image-scanner-jobs","name":"<pod-name>","reconcileID":"e7f07c11-3bb4-46eb-9827-268e51d5c3d7","error":"no waiting state found with reasons [\"ImagePullBackOff\" \"ErrImagePull\"] in pod \"<pod-name>\" with container statuses [{Name:scan-image State:{Waiting:&ContainerStateWaiting{Reason:PodInitializing,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:artifactory.statnett.no/fifty-lab-docker-dev-local/mfrr- …
```
> fix: requeue event when no container state waiting found

- .github/workflows/dependabot-auto-merge.yml
This MR will increase quality of life for maintainers by enabling auto-merge for Dependabot pull requests. Long-time tested in https://github.com/statnett/controller-runtime-viper.
> ci: enable auto-merge for dependabot patch MRs

- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
This reverts commit 0198fc1da0b64ccbf327d4e739cbd3c8fd23648a.
We are struggling with fragile e2e-tests, so we should re-introduce the scan job retries. The problem seems to be in Trivy, and the Trivy-maintainers do not seem to have any appetite to fix it.
> revert: "fix: never retry scan job (#194)"

- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/scan_job_controller.go
This PR replaces some of the cluster-wide RBAC with namespace RBAC in image-scanner namespace. We should always attempt to grant least-privilege permissions...
> fix: tighten cluster-wide RBAC

- .github/workflows/ci.yml
- CONTRIBUTING.md
- Makefile
This reverts commits ea202d0e7062a8ffe520cb56236199846afa7da9 fe6d901a.
I think ginkgo slows down the build, both locally and in CI, and I still cannot see the benefit of using it instead of the standard `go test`.
> revert: "ci(test): use ginkgo to run go tests (#183)"

- .github/workflows/ci.yml
I think now know what's the cause of the fragile e2e tests, and in order to speed up the workflow I suggest removing the extensive logging introduced to dig into this.
> ci(e2e): remove debug logging

- .github/workflows/clean-ghcr.yaml
After we stopped pushing tagged images from PRs, the step removed in this PR is obsolete. Ref. https://github.com/statnett/image-scanner-operator/pkgs/container/image-scanner-operator/versions
> ci: remove obsolete clean image from PR step

- internal/controller/stas/scan_job_controller.go
During an upgrade of our cluster, we got a couple of evicted scan job pods. These resulted in errors in our logs: `expected number of job pods to be 1, got X`. This MR fixes this by ignoring evicted pods when searching for scan job pods.
> fix: don't consider evicted pods when looking for scan job pods

- internal/controller/stas/scan_job_controller.go
The error handling for counting scan job pod was non-intentionally changed in https://github.com/statnett/image-scanner-operator/pull/369. This PR reverts these changes.
> fix: revert change in scan job pod error handling

- Makefile
> chore: upgrade kustomize to latest version (5.0.3)

- Dockerfile
Preparations for bumping dependencies that require Go 1.20.
> chore: bump build image to Go 1.20

- .github/workflows/build-image.yaml
- .github/workflows/clean-ghcr.yaml
- .github/workflows/release-please.yml
After resyncing the main branch in my fork, that triggered a workflow that will never work (in forks). GitHub has limited support for doing this, so the fix is a semi-hack inspired by https://github.com/orgs/community/discussions/26704.
> ci: don't run workflow requiring secrets in forks

- config/prometheus/monitor.yaml
After https://github.com/statnett/image-scanner-operator/pull/442 the `kubernetes_name` label has missing since the `name` label isn't present before after scraping. Hence moving from `relabeling` (before scrape) to `metricRelabeling` (after scrape/before ingestion).
> fix: do relabeling after scraping

- .github/workflows/release-please.yml
There seems to be occasional problems with the release please workflow which makes the release PRs incomplete. This PR will allow users (maintainers) to trigger the workflow manually.
> ci: allow users to trigger release-please workflow

- .github/renovate.json5
Aligning the syntax used with how the official regex matches are defined: https://docs.renovatebot.com/presets-regexManagers/
`\S` means everything non-space. `?:` means a non-capturing group.
> chore: align Renovate marker with upsteam

- .github/renovate.json5
Adding support for `packageName=<packageName>` in Renovate marker.
See https://github.com/renovatebot/renovate/discussions/14885#discussioncomment-2482898 for more info on difference between `depName` and `packageName`.
This PR depends https://github.com/statnett/image-scanner-operator/pull/526.
> ci(renovate): add 'packageName' support in marker

- Makefile
I noticed that dependencies in the Makefile are a bit outdated. Suggesting to add Renovate markers to see if Renovate can suggest upgrades.
> ci: add Renovate markers to Makefile

- test/e2e/workload-scan/scan-daemon-set/00-create.yaml
Removing leftovers from when we ran e2e-tests on Openshift. Noted when causing trouble in https://github.com/statnett/image-scanner-operator/pull/549.
> test(e2e): remove obsolete Openshift daemonset node affinity

- Dockerfile
Which should make it a bit easier to understand the Renovate PRs.
> chore: add patch version to Golang image

- .github/workflows/build-image.yaml
- .github/workflows/ci.yml
- .github/workflows/clean-ghcr.yaml
- .github/workflows/clear-cache.yaml
- .github/workflows/codeql.yml
- .github/workflows/dependabot-auto-merge.yml
- .github/workflows/dependency-review.yml
- .github/workflows/docs.yaml
- .github/workflows/lint-pr.yml
- .github/workflows/release-please.yml
- .github/workflows/scorecards.yml
We introduced step-security tools to see if they could provide some value to use. After almost a year, I don't see much value in them and suggest removing them.
> ci: remove all usage of step-security actions

- .github/workflows/clean-ghcr.yaml
This is a test to see if we can use the new Statnett BOT for the clean GHCR workflow.
> ci: try GHCR cleanup with Statnett BOT token

- .github/renovate.json5
Use https://github.com/statnett/renovate-presets/ as Renovate preset. This is a preset that will be slim, only containing core config changes.
Our current regex dependencies should not changed by this PR.
<details><summary>Current regex dependencies</summary>
</details>
> chore: use statnett renovate preset

- .github/workflows/ci.yml
- api/stas/v1alpha1/containerimagescan_types.go
- go.mod
- go.sum
- internal/controller/stas/types.go
There seems to have been an issue in our CI that allowed a PR with golangci-lint issues to be merged. Not sure why, but I am also disabling the `only-new-issues` option in this PR - as we should not have lint issues on the default branch.
Close https://github.com/statnett/image-scanner-operator/pull/615
> fix: golangci-lint issues

- .github/renovate.json5
To support [organization level sharing of presets](https://docs.renovatebot.com/config-presets/#organization-level-presets), the repo must be named "*renovate-config*".
Depends on: https://github.com/statnett/renovate-config/pull/6
> chore(renovate): change org repo reference

- .github/workflows/lint-pr.yml
After renaming the repository *workflows*  to [github-workflows](https://github.com/statnett/github-workflows), we need to update our import. All file extensions was also [changed to `yaml`](https://github.com/statnett/github-workflows/commit/e5bb6c2ecceffd1d64b217682775a1e2f74ddb6b).
> ci: fix workflow import

- .github/workflows/codeql.yml
This should fix the Renovate warning:
Intentionally removing the trivy-job. We probably don't need multiple scanners. If we want it back, we should add it to the upstream repo.
> ci: use reusable CodeQL workflow

- .github/renovate.json5
This might fix the currently broken Renovate PR. Hopefully, we can promote this to the default config later on.
> ci: add Renovate go mod tidy options

- .github/renovate.json5
After we switched to the default release-please configuration via reusable workflows, the Renovate config should be as default as possible. The Go mod settings are included in the default Renovate config now, so should not be required anymore, ref. https://github.com/statnett/renovate-config/pull/12.
> ci: cleanup obsolete Renovate config

- internal/controller/stas/types.go
- internal/controller/stas/types_test.go
We had an incident  with two replicasets owned by the same deployment and both replicaset pods were crash-looping. One replicaset explicitly used the latest tag, while the other implicitly used the latest tag (no tag). Since both pods use the same image digest, this created a situation where the two owner pods were fighting over the value of `spec.tag` on the shared ContainerImageScan resource.
This PR fixes this issue by making no tag default to the `latest` tag.
> fix: should set tag to latest if no tag on image

- Makefile
- internal/controller/stas/containerimagescan_controller_test.go
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
It seems like we forgot to bump envTest K8s. I don't know if it's possible to get Renovate to care for this, as I have no idea where the releases are mastered. It's downloaded from https://storage.googleapis.com/kubebuilder-tools, but I have no idea where the releases come from.
> test: bump envTest to K8s 1.28

- Makefile
- internal/controller/stas/suite_test.go
In order to avoid attempts to reformat generated files, ref. https://github.com/statnett/image-scanner-operator/pull/668, we should replace goimports with the more flexible alternative https://github.com/daixiang0/gci.
> build: replace goimports with gci

- Dockerfile
- config/manager/manager_patch.yaml
Before we start our migration to SSA, we need to ensure that we can hand over field ownership correctly, ref. https://github.com/kubernetes/kubernetes/issues/99003. Since the K8s client defaults the field owner to the name of the binary, we should rename the binary to get a less generic `manager` value for resources `managedFields`. Currently it may look like this (example):
````yaml
managedFields:
- apiVersion: stas.statnett.no/v1alpha1
fieldsType: FieldsV1
fieldsV1:
'f:metadata':
'f:labels':
.: {}
'f:control-plane': {}
'f:pod-template-hash': {}
'f:ownerReferences':
.: {}
'k:{"uid":"7f0ab8d9-5e1c-45b4-911e-ffe73166e33e"}': {}
'f:spec':
.: {}
'f:digest': {}
'f:ignoreUnfixed': {}
'f:name': {}
'f:tag': {}
'f:workload':
.: {}
'f:containerName': {}
'f:group': {}
'f:kind': {}
'f:name': {} …
```
> chore(ssa): rename binary to get less generic field owner

- config/crd/kustomization.yaml
- config/manager/kustomization.yaml
- config/operator/kustomization.yaml
Fix deprecation warning when running `kustomize build`
```
$ kustomize build
```
> fix(kustomize): migrate away from deprected patchesStrategicMerge

- go.mod
- go.sum
Kubernetes 1.29 requires Go 1.21, so I suggest doing this first.
> chore: bump to go 1.21

- Makefile
It seems like we have some leftovers after migrating from goimports to gci.
> chore: remove unused goimports config

- internal/config/config.go
- internal/controller/stas/suite_test.go
- internal/operator/operator.go
- internal/trivy/scan_job.go
I have been investigating why language-specific vulnerabilities are not detected by the scanner, and I think it's because it currently doesn't work when using the `filesystem` Trivy command. I started looking in this direction after finding https://github.com/aquasecurity/trivy/issues/4133#issuecomment-1664325976, and I want to experiment with the alternative `rootfs` command.
> feat: add rootfs as an alternative to default filesystem Trivy scanning

- internal/controller/stas/suite_test.go
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/operator/operator.go
- internal/trivy/scan_job.go
After trying our `rootfs` scanning in our clusters, it seems like this scanning is a much better default. As a future feature we should probably allow the scanning type to be overridden by workload.
Also adding skip scanning the trivy binary - which currently has at least one HIGH vulnerability. Doing this with a flag - to ensure it overrides any ENVs configuring the same. It just don't make sense to include vulns in the scanner that we "import" into the image.
> feat!: switch to rootfs scanning as new default

- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
It seems like Trivy somehow strips off the first part of the path when walking the filesystem, which makes the `skip-files` argument added in https://github.com/statnett/image-scanner-operator/pull/850 non-effective. This PR is a workaround that sets the argument to a value making it effective.
To debug this, I created a long-running workload configured as our scan jobs.Without this fix, the vulnerabilities present in the trivy binary is reported. Note the path presented in the report!
````
run/image-scanner/trivy (gobinary)
Total: 4 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 1, CRITICAL: 0)
┌────────────────────────────┬────────────────┬──────────┬──────────┬───────────────────┬───────────────┬──────────────────────────────────────────────────────────────┐
│          Library           │ …
```
> fix: use additional skip-files arg in scan job understood by Trivy

- internal/trivy/scan_job.go
- internal/trivy/scan_job_test.go
We observed this error message in one of our clusters today:
````
Job.batch "job-reserved-cross-zonal-capacity-backend-migrations-0.0.-976fb" is invalid: metadata.name: Invalid value: "job-reserved-cross-zonal-capacity-backend-migrations-0.0.-976fb": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
````
I've been looking into this issue: The CIS name is shortened when naming the scan job - to fit into a valid job name. When appending our hash to the CIS name (possibly shortened), we prefix the hash with `-`, and a `-` after a `.` is disallowed by the regex. This PR ensures …
> fix: ensure valid scan job name

- internal/controller/stas/workload_controller.go
This is a leftover from https://github.com/statnett/image-scanner-operator/pull/861. Since we currently don't have a mechanism that allows users to set `minSeverity`, we should ensure it's unset on all CIS resources.
> chore: reset CIS minSeverity in workload controller

- config/default/kustomization.yaml
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
This is another attempt to make the Trivy skip-files configuration work; moving the skip-files config from args to the default job configmap. Also allows the user to eventually override the setting, which could be considered a feature.
> fix: move Trivy skip-files to job configmap

- internal/controller/stas/scan_job_controller.go
Before adding the opt-in creating policy reports from complete scan jobs, I suggest a minor refactoring extracting a function for the logic updating CIS status with the result of the scan.
> refactor: extract function updating CIS status

- .github/workflows/ci.yml
- go.mod
Required to upgrade K8s dependencies. It would be nice if Renovate could suggest PRs like this, but it seems like it insists on a full Go version requirement - which is very uncommon and something I would like to avoid.
Also fixing a missing requirement on Go in the e2e-tests job detected when attempting to perform a simple upgrade.
> chore: upgrade Go mod requirements to Go 1.22

- Makefile
- config/crd/bases/stas.statnett.no_containerimagescans.yaml
Replacement for https://github.com/statnett/image-scanner-operator/pull/902, as a regen is required.
Close https://github.com/statnett/image-scanner-operator/pull/902
> chore(deps): update module sigs.k8s.io/controller-tools to v0.15.0

- .github/workflows/clean-ghcr.yaml
It seems like we forgot to update the link when the workflows project was renamed.
> ci: fix broken link to reusable workflow

- go.mod
It seems like Renovate adds it, and I would prefer to avoid getting PRs for bumping the toolchain.
> chore: remove toolchain from go.mod

- .github/workflows/ci.yml
Ref. https://github.com/advisories/GHSA-ghm2-rq8q-wrhc
https://github.com/statnett/image-scanner-operator/pull/947 has broken CI.
> ci: fix verify-changed-files GH security advisory

- Makefile
- internal/client/applyconfiguration/stas/v1alpha1/containerimagescanstatus.go
- internal/wg-policy/applyconfiguration/reports.x-k8s.io/v1beta2/clusterpolicyreport.go
- internal/wg-policy/applyconfiguration/reports.x-k8s.io/v1beta2/policyreport.go
- internal/wg-policy/applyconfiguration/reports.x-k8s.io/v1beta2/policyreportconfiguration.go
- internal/wg-policy/applyconfiguration/reports.x-k8s.io/v1beta2/policyreportresult.go
Alternative to https://github.com/statnett/image-scanner-operator/pull/897 - fixing the breaking changes.
~~I wasn't able to generate applyconfigurations for https://github.com/kubernetes-sigs/wg-policy-prototypes resources with the newer version, but I suggest we leave it for now - as we haven't started using them.~~ UPDATE: This issue seems to be caused by a regression in v0.30.0 - this a fix that will be released with v0.30.1. And now released.
> chore(deps): update module github.com/kubernetes/code-generator to v0.30.1

- internal/controller/stas/workload_controller.go
Somehow this change is required to make IDEA happy. No idea why,
> build: add type constraint to avoid warning in IDEA

- internal/controller/stas/indexer.go
- internal/controller/stas/workload_controller.go
- internal/controller/stas/workload_controller_test.go
Simplifies migration to server side apply. Can now safely overwrite (not merge) container image scan owner referances
> feat: reconcile cis with all owning pods

- config/default/kustomization.yaml
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/trivy/scan_job.go
This should resolve the malfunctioning skip-files configuration causing trivy binary vulnerabilities to show up in user scan reports.
> fix: move mount of trivy binary to /run/image-scanner/trivy

- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/containerimagescan_status.go
- internal/controller/stas/scan_job_controller.go
This eliminates some delicate duplicate code and makes the code more DRY.
> refactor: introduce containerImageScanStatusPatch to reduce code duplication

- Makefile
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- test/e2e-config/k3d-config.yml
I'm having issues running tests from my IDE, and it seems like the problem is that my IDE finds a locally installed version of K8s envTest (1.30). To mend this, I suggest upgrading to the latest version in CI. This makes `make test` behave as in my IDE.
I also noticed that the k3s version was outdated, so it's also fixed in this PR. I suspect an invalid Renovate expression to be the culprit, so trying with a major simplification that I know works for other images.
> test: bump K8s envTest and k3s versions

- cmd/main.go
- go.mod
- go.sum
- internal/config/feature/feature.go
- internal/config/feature_gate.go
- internal/controller/stas/containerimagescan_status.go
- internal/controller/stas/policy_report.go
- internal/controller/stas/scan_job_controller.go
- internal/controller/stas/scan_job_controller_test.go
- internal/controller/stas/ssa_client.go
- internal/controller/stas/suite_test.go
- internal/operator/operator.go
This PR adds our first feature gate! 🎉 The feature gate is currently disabled by default. If the feature gate is enabled, the operator will create [wgpolicyk8s.io/v1alpha2 PolicyReport](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/crd/v1alpha2/wgpolicyk8s.io_policyreports.yaml) resources for completed scan jobs.
The proposed mapping from the Trivy scan results to the policy report is inspired by [trivy-operator-polr-adapter](https://github.com/fjogeleit/trivy-operator-polr-adapter/blob/main/pkg/adapters/vulnr/mapper.go).
The Kubernetes policy working group has defined newer/improved PolicyReport APIs, but the proposed group/version is currently used, and CRD is installed, by Kyverno (version 1.12.5). The API is also the only API currently supported by …
> feat: opt-in creating wg-policy PolicyReport

- internal/controller/stas/policy_report.go
After enabling the PolicyReport alpha feature gate in one of our clusters, we observe the following error:
````
[results[0].severity: Unsupported value: \"\":
supported values: \"critical\", \"high\", \"low\", \"medium\", \"info\"
````
The `severity` field is optional in the `PolicyReport` API, so I suggest not setting the field if `severity` is UKNOWN in scan results.
> fix: mapping of severity UNKNOWN to policy report

- test/e2e-config/k3d-config.yml
While debugging another issue, I noticed that k3d complained about using outdated config.
> test(e2e): migrate k3d config to latest version

- test/e2e/scenario/vulnerability-overflow/00-assert.yaml
- test/e2e/scenario_disabled/private-image/00-assert.yaml
- test/e2e/workload-scan/scan-cron-job/01-assert.yaml
- test/e2e/workload-scan/scan-daemon-set/01-assert.yaml
- test/e2e/workload-scan/scan-deployment/01-assert.yaml
- test/e2e/workload-scan/scan-job/01-assert.yaml
- test/e2e/workload-scan/scan-pod/01-assert.yaml
- test/e2e/workload-scan/scan-replica-set/01-assert.yaml
- test/e2e/workload-scan/scan-stateful-set/01-assert.yaml
It turns out that chainsaw doesn't read the assert resources as kuttl did, so we have been running without asserting tests since https://github.com/statnett/image-scanner-operator/pull/794. 😆 
@eddycharly is fixing this issue in chainsaw now, but until a new release of chainsaw is available, this PR implements a [workaround suggested on Slack](https://kubernetes.slack.com/archives/C067LUFL43U/p1721574298810959?thread_ts=1721566440.213909&cid=C067LUFL43U).
> test(e2e): make chainsaw really assert status

- config/e2e-test/kustomization.yaml
I found an "experiment" leftover in the e2e-test config. In this PR I disable the Trivy "slow" mode which appears to have little effect.
> test(e2e): don't use Trivy "slow" mode

- test/e2e/workload-scan/scan-cron-job/00-assert.yaml
- test/e2e/workload-scan/scan-cron-job/00-create.yaml
- test/e2e/workload-scan/scan-cron-job/01-assert.yaml
- test/e2e/workload-scan/scan-daemon-set/00-assert.yaml
- test/e2e/workload-scan/scan-daemon-set/00-create.yaml
- test/e2e/workload-scan/scan-daemon-set/01-assert.yaml
- test/e2e/workload-scan/scan-deployment/00-assert.yaml
- test/e2e/workload-scan/scan-deployment/00-create.yaml
- test/e2e/workload-scan/scan-deployment/01-assert.yaml
- test/e2e/workload-scan/scan-job/00-assert.yaml
- test/e2e/workload-scan/scan-job/00-create.yaml
- test/e2e/workload-scan/scan-job/01-assert.yaml
- test/e2e/workload-scan/scan-pod/00-assert.yaml
- test/e2e/workload-scan/scan-pod/00-create.yaml
- test/e2e/workload-scan/scan-pod/01-assert.yaml
- test/e2e/workload-scan/scan-replica-set/00-assert.yaml
- test/e2e/workload-scan/scan-replica-set/00-create.yaml
- test/e2e/workload-scan/scan-replica-set/01-assert.yaml
- test/e2e/workload-scan/scan-stateful-set/00-assert.yaml
- test/e2e/workload-scan/scan-stateful-set/00-create.yaml
- test/e2e/workload-scan/scan-stateful-set/01-assert.yaml
It seems like we are using an old nginx image with a lot of vulnerabilities. This PR bumps the image to the digest of the current latest tag.
> test(e2e): refresh nginx test image

- config/e2e-test/kustomization.yaml
- config/rbac/role.yaml
- config/wg-policy/crd/kustomization.yaml
- internal/controller/stas/scan_job_controller.go
- test/e2e/scenario/policy-report/00-assert.yaml
- test/e2e/scenario/policy-report/00-create.yaml
- test/e2e/scenario/policy-report/01-assert.yaml
- test/e2e/scenario/policy-report/chainsaw-test.yaml
When trying out the new PolicyReport feature gate, we discovered that the required RBAC wasn't granted. This PR fixes this and also adds a simple e2e-test verifying that the feature gate works.
> fix: add missing PolicyReport RBAC

- Dockerfile
Observed a warning in another PR: https://github.com/statnett/image-scanner-operator/pull/1041/files
> chore: consistent Dockerfile casing

- test/e2e-config/.chainsaw.yaml
While debugging another issue, I noticed that we are not using the latest Chainsaw config version.
> test(e2e): migrate chainsaw config to latest version

- internal/controller/stas/indexer.go
- internal/controller/stas/predicates.go
- internal/controller/stas/scan_job_controller.go
Kubernetes 1.31 seems to introduce a new Job status (condition). This breaks the current (dumb) logic. This PR tries to fix this logic, making us support Kubernetes 1.31.
> fix: better job condition logic (support K8s 1.31)

- Makefile
- test/e2e-config/k3d-config.yml
No idea why the renovate-image marker on the k3s image doesn't work. Any idea @mikaelol?
> chore: bump k8s/k3s to 1.31

- config/e2e-test/kustomization.yaml
Most Renovate PRs are now failing, and I suspect it's because our e2e-tests are being rate-limited by GHCR. I am hoping that switching to the unofficial DB mirror can help.
https://github.com/statnett/image-scanner-operator/pulls
> ci(e2e-test): try unofficial Trivy DB to mend failing CI

- Makefile
- internal/controller/stas/scan_job_controller_test.go
It seems like the api-server has stronger validations in K8s 1.32.
> test(deps): bump envtest to 1.32.0

- Dockerfile
I don't think this is a real issue, but I noticed Renovate displaying an error message on the Dependency Dashboard issue, so I checked the [upstream repo](https://github.com/GoogleContainerTools/distroless?tab=readme-ov-file#how-do-i-use-distroless-images). It seems like we are using a deprecated distroless image name. This PR uses the non-deprecated name.
> chore: use non-deprecated distroless image ref

- go.mod
- go.sum
- internal/hash/strings.go
- internal/operator/decode_hooks.go
- internal/operator/operator.go
By coincidence, I noticed that mitchellh has archived some of his repos. Here is some notes about the successors: https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc
> fix: migrate away from archived mitchellh modules

- internal/config/config.go
- internal/controller/stas/suite_test.go
- internal/controller/stas/testdata/scan-job/expected-scan-job.yaml
- internal/operator/operator.go
- internal/trivy/scan_job.go
We want to keep scan jobs around shorter than the current default of two hours. This PR surfaces the Kubernetes Job `TTLSecondsAfterFinished` field.
> feat: make scan job lifetime configurable

- internal/operator/operator.go
Enables the quite recent controller-runtime priority queue added in https://github.com/kubernetes-sigs/controller-runtime/pull/3014, to prioritize new/changed resources over startup events and/or resync/requeue events.
This relates to the problem described in https://github.com/statnett/image-scanner-operator/pull/1289. Our smoke tests are often failing in this busy cluster, and hopefully, a priority queue could improve this.
> fix: enable controller-runtime priority queue

- internal/controller/stas/suite_test.go
- internal/controller/stas/workload_controller_test.go
Preparations for https://github.com/statnett/image-scanner-operator/pull/1309 - ensuring test pods are considered ready/current by status.
Also shorter timeout needed to work on this.
> test: set test pods ready to prepare for more delicate logic

- internal/controller/stas/predicates.go
- internal/controller/stas/workload_controller.go
After https://github.com/statnett/image-scanner-operator/pull/1289 we observe a huge reduction in CIS resources in our clusters. I suspect we filter out pods based on stale state. This replaces the predicate with more delicate handling at the start of the reconciling loop.
Reverts https://github.com/statnett/image-scanner-operator/pull/1289
Statuses: https://github.com/kubernetes-sigs/cli-utils/blob/1a9b04556153279603429504ed7ef75c82be6da6/pkg/kstatus/status/status.go#L22-L28
> fix: improve use of kstatus to reconcile pods

- .github/workflows/ci.yml
- config/crd/bases/stas.statnett.no_containerimagescans.yaml
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
And all our CI is currently borked because GH deleted the tj-actions organization.
I did a quick search for simple replacements, and while it doesn't do the same, I think https://github.com/int128/update-generated-files-action should achieve the goal of ensuring that generated files are up-to-date.
> ci: replacement for hacked tj-actions/verify-changed-files

- .github/workflows/ci.yml
Reverts https://github.com/statnett/image-scanner-operator/pull/1323, but also upgrades to the latest release.
> ci: reintroduced previously hacked tj-actions/verify-changed-files

- internal/controller/stas/workload_controller.go
To avoid the event queue being filled with restarting (unhealthy) pods. We are struggling to operate in one of our clusters with a lot of "garbage" workloads.
> fix: don't requeue any pod events

- release-please-config.json
After working with release-please configuration in another project, I have learned something new.
This PR adjusts the release-please configuration to improve the following:
- `always-update: true` to make release-please always update the release PR. We only allow fast-forward merges in this project, so without this a user must rebase anyway.
- add `sentence-case` plugin - which will allow us to be more lenient with PR titles.
- add JSON schema reference to better support IDEs.
- `bump-patch-for-minor-pre-major: false` (the default) to make new feature more "visible" in releases.
Some references:
- https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
- https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#sentence-case
> ci(release): improve release-please configuration

- internal/operator/operator.go
Reverts statnett/image-scanner-operator#1362
It seems like thousands of jobs in this cluster was causing the issue, and the priority queue is no longer considered the culprit.
> revert: "revert: "fix: enable controller-runtime priority queue""

- internal/config/config.go
- internal/controller/stas/containerimagescan_controller.go
- internal/operator/operator.go
`workqueue_depth` is currently 0, while `workqueue_retries` is very high (at times > 1000/second). Adding a wait-for-vacant-job-slot feature to not run through and requeue the entire queue, but instead wait a bit when a scan job cannot be scheduled.
Hopfully now showing a real `workqueue_depth` value.
> feat: wait for vacant slot when max scan jobs running

- internal/controller/stas/predicates.go
- internal/controller/stas/workload_controller.go
ImagePullBackOff pods are currently requeued every second, they don't need to be enqueued at all
> fix: dont reconcile backoff pods

- internal/operator/operator.go
typo in https://github.com/statnett/image-scanner-operator/pull/1382
ref https://github.com/statnett/image-scanner-operator/blob/f84fa69885cce2061410c82c5294605f0fd8d019/internal/config/config.go#L24
> fix: active-scan-job-max-wait-duration flag

- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/predicates.go
Avoid enqueuing cis that does not need new scan
Could also be done as an early exit in the reconcile, but I think this will work as we have the scheduling ticker.
> fix: dont reconcile when scan not needed

- internal/config/config.go
- internal/controller/stas/containerimagescan_controller.go
- internal/operator/operator.go
Fixed the problem with workqueue always being zero, but do not want this time-based block here.
Could in the future wait on a golang channel from the controller working with jobs, and block untill a slot is known to be available.
> chore!: remove wait feature

- internal/controller/stas/containerimagescan_controller.go
Made a predicate in https://github.com/statnett/image-scanner-operator/pull/1394, and the ticker performs it's own check https://github.com/statnett/image-scanner-operator/blob/aadaee5bae0f06d074503ad505fe49993ac8c528/internal/controller/stas/containerimagescan_controller.go#L56
Should therefore never occur here
> fix: remove scanned within interval check

- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/containerimagescan_controller_test.go
- guarantees images that are never scanned to be requeued every 3s
- requeues scanned images with a higher interval (based on how much overdue a new scan) to not contantly process all
- hopefully fixing the workqueue_depth metic, which is currently stuck at 0
> fix: guarantee fast requeue for images never scanned

- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/containerimagescan_controller_test.go
reverts https://github.com/statnett/image-scanner-operator/pull/1422
Does make that much sense after https://github.com/statnett/image-scanner-operator/pull/1424
> revert: fix: guarantee fast requeue for images never scanned

- .golangci.yml
- internal/controller/stas/containerimagescan_status.go
- internal/metrics/collector.go
The wsl linter is marked as deprecated in golangci-lint and replaced with the new wsl_v5 linter.
> chore: migrate deprecated wsl linter to wsl_v5

- .golangci.yml
- CONTRIBUTING.md
- Makefile
I just learned that golangci-lint has built-in support for the gci formatter.
Closes https://github.com/statnett/image-scanner-operator/pull/1481
> chore: remove direct dependency to the GCI formatter

- internal/controller/stas/containerimagescan_status.go
- internal/controller/stas/policy_report.go
- internal/controller/stas/ssa_client.go
- internal/controller/stas/workload_controller.go
We have now upgraded controller-runtime to the latest release, which contains a new `client.Apply` function to perform native SSA requests.
> refactor: migrate to new c/r Apply function

- internal/controller/stas/containerimagescan_controller.go
- internal/controller/stas/policy_report.go
- internal/controller/stas/scan_job_controller.go
This appears to be an oversight in https://github.com/statnett/image-scanner-operator/pull/1424. We noticed this when enabling e2e-tests for policy reports in a cluster where all tests run in the same namespace. The cronjob test CIS reuses the scan results of the job test, but no policy report.
> fix: also create policy report when reusing report from CIS
